

# Wii Cursor Monitor

enabled=true

# PLAYER 1 — Framework internal display
p1_manufacturer=BOE
p1_model=eDP-1-NE135A1M-NY1
p1_theme=Wii Pointer

# PLAYER 2 — Acer
p2_manufacturer=Acer Technologies
p2_model=KA220HQ
p2_theme=Wii Pointer Player 2

# PLAYER 3 — Samsung TV
p3_manufacturer=Samsung Electric Company
p3_model=
p3_theme=Wii Pointer Player 3

# PLAYER 4 — custom/recovered display
p4_manufacturer=Invalid Vendor Codename - RTK
p4_model=RTK FHD
p4_serial=L56051794302
p4_theme=Wii Pointer Player 4
